### ISSUE TITLE
arrays problems documentation

### ISSUE THREAD

**Issue by AmirAhmadzadeh** [AmirAhmadzadeh/ds-algorithms#5]
Regarding this matter, it is necessary to tidy up the readme specifically in the arrays section.

links to the readme files: 

https://github.com/AmirAhmadzadeh/ds-algorithms/blob/main/ts/1.array/problem.md 
https://github.com/AmirAhmadzadeh/ds-algorithms/blob/main/golang/1.array/problem.md
https://github.com/AmirAhmadzadeh/ds-algorithms/blob/main/rs/1.array/problems.md 

# TODO

1. Please enhance the descriptions of each issue in a more detailed and informative manner.
2. update the test cases.
3. tidy up the code for the challenges

**Comment by vFlagz** [comment]
i'm working on this issue

**Comment by vFlagz** [comment]
[todo #1 PR](https://github.com/AmirAhmadzadeh/ds-algorithms/pull/20)

i'm going to work on todo #2

**Comment by AmirAhmadzadeh** [comment]
Great thanks @vFlagz
